chore: improve annotations
python-attrs/cattrs pull request #288
Opened 2022-07-07 09:22 UTC by aarnphm

As I was working with cattrs recently, I notice there are some places where
annotations are still missing.

Hopefully this PR address most of the popular API to be annotated.

2022-07-07 14:14 UTC, Tinche requested changes
Left a few comments :)

I would also suggest rebasing on top of `tin/copy` instead of `main`.

Thanks!

2022-07-07 14:14 UTC, Tinche commented on src/cattrs/converters.py
> +    def unstructure(self, obj: Any, unstructure_as: Optional[Any] = None) -> Any:
`Optional[Any]` doesn't really make sense to me as a type annotation, as `Any` already includes every value, so `None` too. Some people think it makes intention clearer; I don't buy that though, it's just line noise to me.

2022-07-07 14:14 UTC, Tinche commented on src/cattrs/converters.py
> +    def _unstructure_enum(self, obj: Enum):
```suggestion
    def _unstructure_enum(self, obj: Enum) -> Any:
```

2022-07-07 14:14 UTC, Tinche commented on src/cattrs/converters.py
> +    def _structure_error(self, _, cl: Any) -> None:
`None` is incorrect as the return value here. It should actually be `NoReturn`, you can check if our currenct dependency versions allow us to use this.

2022-07-07 14:14 UTC, Tinche commented on src/cattrs/converters.py
> +    def gen_unstructure_iterable(self, cl: Any, unstructure_to: Optional[Any] = None):
Same comment as above.

2022-07-07 14:14 UTC, Tinche commented on src/cattrs/converters.py
> +        self, cl: Any, unstructure_to: Optional[Any] = None
Same comment as above.

2022-07-07 14:14 UTC, Tinche commented on src/cattrs/converters.py
> +        unstructure_to: Optional[Any] = None,
Same comment as above.

2022-07-07 14:14 UTC, Tinche commented on src/cattrs/disambiguators.py
> +        # type: (Mapping[Any, Any]) -> Optional[Type]
You can turn this into a proper type annotation, it's a leftover from when this code still supported Python 2

2022-07-07 14:45 UTC, aarnphm commented on src/cattrs/converters.py
> +    def unstructure(self, obj: Any, unstructure_as: Optional[Any] = None) -> Any:
Make sense.

2022-07-07 14:54 UTC, aarnphm commented on src/cattrs/disambiguators.py
> +        # type: (Mapping[Any, Any]) -> Optional[Type]
sounds good will do.

2022-07-07 15:11 UTC, aarnphm commented on src/cattrs/converters.py
> +    def _structure_error(self, _, cl: Any) -> None:
`NoReturn` is available since 3.6

2022-07-08 19:17 UTC, aarnphm commented
cc @Tinche whenever you have time. This is just dx improvement, so it would be nice to include in 22.2. Otherwise there is no rush.

2022-09-11 21:05 UTC, aarnphm commented
I will close this now since I believe you also update annotations on the copy branch.

2022-09-11 21:05 UTC, closed without merging

2022-09-11 22:21 UTC, Tinche commented
Ah sorry, the copy branch took a lot longer than I was expecting. I don't think I have all of these though, if you reopen I will merge in.

2022-09-12 09:55 UTC, aarnphm commented
sg, let me check for any merge config.