Allows use of `typing_extensions.Annotated` when python version is less than `3.9`
python-attrs/cattrs pull request #366
Opened 2023-05-22 12:45 UTC by jdoiro3

Currently, the use of `typing_extensions.Annotated` doesn't work. This PR adds support for the type when the version of Python is less that `3.9` (i.e., the user can't use `typing.Annotated`).

2023-05-22 12:49 UTC, Tinche commented
Cool! Can you add a changelog entry too? And maybe a line to the Annotated sections in the docs?

2023-05-22 13:15 UTC, jdoiro3 commented
> Cool! Can you add a changelog entry too? And maybe a line to the Annotated sections in the docs?

Just added an entry under the current unreleased version. Let me know if any other changes are needed.

2023-05-22 16:47 UTC, Tinche requested changes
Please rebase and let's get this merged in.

2023-05-22 16:47 UTC, Tinche commented on src/cattrs/_compat.py
> +        return get_origin(type) == Annotated
I think you can use `is` here?

2023-05-22 17:19 UTC, jdoiro3 commented on src/cattrs/_compat.py
> +        return get_origin(type) == Annotated
Fixed.

2023-05-22 18:22 UTC, jdoiro3 commented
@Tinche, not sure why CI isn't running but this looks good to go.

2023-05-23 00:13 UTC, Tinche commented
I reran the action, looks like there's a linting issue now.

2023-05-23 11:17 UTC, jdoiro3 commented
@Tinche, can you run CI again? I removed the `get_origin` import from `typing_extensions` since it seems to be the same implementation as `typing`. Wasn't sure it was.

2023-05-23 11:48 UTC, jdoiro3 commented
Looks like everything passes except `pre-commit.ci`.

2023-05-23 15:13 UTC, Tinche commented
Sweet. I don't actually know where the pre-commit.ci is defined. Maybe the python-attrs organization?

2023-05-23 15:14 UTC, Tinche approved these changes

2023-05-23 15:14 UTC, merged