Use the un-underscored name if no alias attribute is there.
python-attrs/cattrs pull request #416
Opened 2023-08-14 16:07 UTC by jap

This appears to be caused by a thinko in #391, this fixes it again.

2023-08-14 17:08 UTC, Tinche commented
Ah, cool. Can you add a changelog note? And a simple test would be great so it doesn't happen again.

2023-08-15 09:35 UTC, jap commented
Actually -- given that `cattrs` depends on modern `attrs` and this is just compat code, let me simplify it!

2023-08-30 21:08 UTC, Tinche commented
Howdy, any progress on this? Trying to plan the next release.

2023-09-01 13:41 UTC, jap commented
Whoops, sorry - forgot about this PR, working on an updated version now!

2023-09-03 23:29 UTC, Tinche requested changes
Looks good, left a comment

2023-09-03 23:29 UTC, Tinche commented on tests/test_converter.py
> +    converter = Converter()
I think you should be testing this with a `BaseConverter` to hit the changed code path, the `Converter` uses different machinery.

2023-09-04 21:52 UTC, Tinche commented
Just a small note, I'll be away for the next 3 weeks on a family trip and I can continue reviewing this after I'm back!

2023-09-23 15:53 UTC, Tinche commented
I want to get the next release out so I fixed this myself. Thanks!

2023-09-23 15:53 UTC, merged